[[CURRENCIES]]
code="SGT"
issuer="GDC2PGULFHNC5QLBCMHYMW44OECRTOQO64LO7LZ2KGZ4LRY2INEELG4M"
name="Sagatama Token"
desc="Token reward resmi Sagatama Mart, dipakai untuk poin belanja dan potongan harga di ekosistem Sagatama."
image="https://sagatama-mart.vercel.app/logo-sagatama.png"
