[[CURRENCIES]]
code="SGT"
issuer="GBZ4GLCFI3NHLQQGVZE5OYYEC35LLJASKSOYWBUCBPQCBRWGJE3FKCMS"
name="Sagatama Token"
desc="Token reward resmi Sagatama Mart, dipakai untuk poin belanja dan potongan harga di ekosistem Sagatama."
image="https://sagatama-mart.vercel.app/sgt-token_logo.png"
